#pragma once

#include <cstdint>
#include <string>
#include <vector>

namespace solc
{

enum class ASTGroup : uint8_t
{
  NONE = 0,
  STMT,
  ENUM,
  TYPE,
  VAR,
  FUNC,
  EXPR_BINARY_OPERATOR,
  EXPR_COMPARE_OPERATOR,
  EXPR_BOOLEAN_OPERATOR,
  EXPR_ASSIGN_OPERATOR,
  EXPR_PREFIX_OPERATOR,
  EXPR_OPERAND,
  TEMPLATE,
  VISIBILITY_MARKER,
  INITLIST,
};

#define __AST_DEF(group, id) (((uint8_t)(group) & 0xFF) << 8) | ((id) & 0xFF)
enum struct ASTType : uint16_t
{
  ERR = __AST_DEF (ASTGroup::NONE, 0),

  PROG = __AST_DEF (ASTGroup::NONE, 1),
  EXPR = __AST_DEF (ASTGroup::NONE, 2),
  MODULE = __AST_DEF (ASTGroup::NONE, 3),
  IMPORT = __AST_DEF (ASTGroup::NONE, 4),
  TYPEDEF = __AST_DEF (ASTGroup::NONE, 5),
  EXPORT = __AST_DEF (ASTGroup::NONE, 6),
  MODIFIER = __AST_DEF (ASTGroup::NONE, 7),
  NONE = __AST_DEF (ASTGroup::NONE, 8),
  LABEL = __AST_DEF (ASTGroup::NONE, 9),
  VARIADIC = __AST_DEF (ASTGroup::NONE, 10),
  TEMPLATE = __AST_DEF (ASTGroup::NONE, 11),
  STRUCT = __AST_DEF (ASTGroup::NONE, 12),
  UNION = __AST_DEF (ASTGroup::NONE, 13),
  NAMESPACE = __AST_DEF (ASTGroup::NONE, 14),
  INITLIST = __AST_DEF (ASTGroup::NONE, 15),
  GENERIC_TYPE_LIST = __AST_DEF (ASTGroup::NONE, 16),
  PREFIX_EXPR = __AST_DEF (ASTGroup::NONE, 17),

  STMT_LIST = __AST_DEF (ASTGroup::STMT, 0),
  STMT_RETURN = __AST_DEF (ASTGroup::STMT, 1),
  STMT_GOTO = __AST_DEF (ASTGroup::STMT, 2),
  STMT_LABEL = __AST_DEF (ASTGroup::STMT, 3),
  STMT_BREAK = __AST_DEF (ASTGroup::STMT, 4),
  STMT_CONTINUE = __AST_DEF (ASTGroup::STMT, 5),
  STMT_WHILE = __AST_DEF (ASTGroup::STMT, 6),
  STMT_FOR = __AST_DEF (ASTGroup::STMT, 7),
  STMT_DOWHILE = __AST_DEF (ASTGroup::STMT, 8),
  STMT_EXPR = __AST_DEF (ASTGroup::STMT, 9),
  STMT_SWITCH = __AST_DEF (ASTGroup::STMT, 10),
  STMT_CASE = __AST_DEF (ASTGroup::STMT, 11),
  STMT_DEFAULT = __AST_DEF (ASTGroup::STMT, 12),
  STMT_DEFER = __AST_DEF (ASTGroup::STMT, 13),
  STMT_IF = __AST_DEF (ASTGroup::STMT, 14),
  STMT_ELSE = __AST_DEF (ASTGroup::STMT, 15),

  ENUM_DEF = __AST_DEF (ASTGroup::ENUM, 0),
  ENUM_ELEMENT = __AST_DEF (ASTGroup::ENUM, 1),

  TYPE_PLAIN = __AST_DEF (ASTGroup::TYPE, 0),
  TYPE_ARRAY = __AST_DEF (ASTGroup::TYPE, 1),
  TYPE_POINTER = __AST_DEF (ASTGroup::TYPE, 2),
  TYPE_FUNCPTR = __AST_DEF (ASTGroup::TYPE, 3),

  VAR_DECL = __AST_DEF (ASTGroup::VAR, 0),
  VAR_DEF = __AST_DEF (ASTGroup::VAR, 1),

  FUNC_PROTO = __AST_DEF (ASTGroup::FUNC, 0),
  FUNC_DEF = __AST_DEF (ASTGroup::FUNC, 1),
  FUNC_ARGLIST = __AST_DEF (ASTGroup::FUNC, 2),

  EXPR_BINARY_OPERATOR_ADD = __AST_DEF (ASTGroup::EXPR_BINARY_OPERATOR, 0),
  EXPR_BINARY_OPERATOR_SUB = __AST_DEF (ASTGroup::EXPR_BINARY_OPERATOR, 1),
  EXPR_BINARY_OPERATOR_MUL = __AST_DEF (ASTGroup::EXPR_BINARY_OPERATOR, 2),
  EXPR_BINARY_OPERATOR_DIV = __AST_DEF (ASTGroup::EXPR_BINARY_OPERATOR, 3),
  EXPR_BINARY_OPERATOR_MOD = __AST_DEF (ASTGroup::EXPR_BINARY_OPERATOR, 4),
  EXPR_BINARY_OPERATOR_SHL = __AST_DEF (ASTGroup::EXPR_BINARY_OPERATOR, 5),
  EXPR_BINARY_OPERATOR_SHR = __AST_DEF (ASTGroup::EXPR_BINARY_OPERATOR, 6),
  EXPR_BINARY_OPERATOR_AND = __AST_DEF (ASTGroup::EXPR_BINARY_OPERATOR, 7),
  EXPR_BINARY_OPERATOR_OR = __AST_DEF (ASTGroup::EXPR_BINARY_OPERATOR, 8),
  EXPR_BINARY_OPERATOR_XOR = __AST_DEF (ASTGroup::EXPR_BINARY_OPERATOR, 9),

  EXPR_COMPARE_OPERATOR_EQ = __AST_DEF (ASTGroup::EXPR_COMPARE_OPERATOR, 0),
  EXPR_COMPARE_OPERATOR_NOTEQ = __AST_DEF (ASTGroup::EXPR_COMPARE_OPERATOR, 1),
  EXPR_COMPARE_OPERATOR_LTHAN = __AST_DEF (ASTGroup::EXPR_COMPARE_OPERATOR, 2),
  EXPR_COMPARE_OPERATOR_GTHAN = __AST_DEF (ASTGroup::EXPR_COMPARE_OPERATOR, 3),
  EXPR_COMPARE_OPERATOR_LTHANEQ
  = __AST_DEF (ASTGroup::EXPR_COMPARE_OPERATOR, 4),
  EXPR_COMPARE_OPERATOR_GTHANEQ
  = __AST_DEF (ASTGroup::EXPR_COMPARE_OPERATOR, 5),

  EXPR_BOOLEAN_OPERATOR_AND = __AST_DEF (ASTGroup::EXPR_BOOLEAN_OPERATOR, 0),
  EXPR_BOOLEAN_OPERATOR_OR = __AST_DEF (ASTGroup::EXPR_BOOLEAN_OPERATOR, 1),

  EXPR_ASSIGN_OPERATOR_EQ = __AST_DEF (ASTGroup::EXPR_ASSIGN_OPERATOR, 0),
  EXPR_ASSIGN_OPERATOR_ADDEQ = __AST_DEF (ASTGroup::EXPR_ASSIGN_OPERATOR, 1),
  EXPR_ASSIGN_OPERATOR_SUBEQ = __AST_DEF (ASTGroup::EXPR_ASSIGN_OPERATOR, 2),
  EXPR_ASSIGN_OPERATOR_MULEQ = __AST_DEF (ASTGroup::EXPR_ASSIGN_OPERATOR, 3),
  EXPR_ASSIGN_OPERATOR_DIVEQ = __AST_DEF (ASTGroup::EXPR_ASSIGN_OPERATOR, 4),
  EXPR_ASSIGN_OPERATOR_MODEQ = __AST_DEF (ASTGroup::EXPR_ASSIGN_OPERATOR, 5),
  EXPR_ASSIGN_OPERATOR_SHLEQ = __AST_DEF (ASTGroup::EXPR_ASSIGN_OPERATOR, 6),
  EXPR_ASSIGN_OPERATOR_SHREQ = __AST_DEF (ASTGroup::EXPR_ASSIGN_OPERATOR, 7),
  EXPR_ASSIGN_OPERATOR_ANDEQ = __AST_DEF (ASTGroup::EXPR_ASSIGN_OPERATOR, 8),
  EXPR_ASSIGN_OPERATOR_OREQ = __AST_DEF (ASTGroup::EXPR_ASSIGN_OPERATOR, 9),
  EXPR_ASSIGN_OPERATOR_XOREQ = __AST_DEF (ASTGroup::EXPR_ASSIGN_OPERATOR, 10),

  EXPR_PREFIX_OPERATOR_NOT = __AST_DEF (ASTGroup::EXPR_PREFIX_OPERATOR, 0),
  EXPR_PREFIX_OPERATOR_BNOT = __AST_DEF (ASTGroup::EXPR_PREFIX_OPERATOR, 1),
  EXPR_PREFIX_OPERATOR_NEG = __AST_DEF (ASTGroup::EXPR_PREFIX_OPERATOR, 2),
  EXPR_PREFIX_OPERATOR_DEREF = __AST_DEF (ASTGroup::EXPR_PREFIX_OPERATOR, 3),
  EXPR_PREFIX_OPERATOR_ADDRESS = __AST_DEF (ASTGroup::EXPR_PREFIX_OPERATOR, 4),

  EXPR_OPERAND_IDENTIFIER = __AST_DEF (ASTGroup::EXPR_OPERAND, 0),
  EXPR_OPERAND_NUM = __AST_DEF (ASTGroup::EXPR_OPERAND, 1),
  EXPR_OPERAND_NUMFLOAT = __AST_DEF (ASTGroup::EXPR_OPERAND, 2),
  EXPR_OPERAND_ARRAY_ELEMENT = __AST_DEF (ASTGroup::EXPR_OPERAND, 3),
  EXPR_OPERAND_CAST_TO = __AST_DEF (ASTGroup::EXPR_OPERAND, 4),
  EXPR_OPERAND_CALL = __AST_DEF (ASTGroup::EXPR_OPERAND, 5),
  EXPR_OPERAND_NUMTYPESPEC = __AST_DEF (ASTGroup::EXPR_OPERAND, 6),
  EXPR_OPERAND_STRING = __AST_DEF (ASTGroup::EXPR_OPERAND, 7),
  EXPR_OPERAND_SYMBOL = __AST_DEF (ASTGroup::EXPR_OPERAND, 8),
  EXPR_OPERAND_ACCESS_MEMBER = __AST_DEF (ASTGroup::EXPR_OPERAND, 9),

  TEMPLATE_TYPE_LIST = __AST_DEF (ASTGroup::TEMPLATE, 0),
  TEMPLATE_TYPE = __AST_DEF (ASTGroup::TEMPLATE, 1),

  VISIBILITY_MARKER_PUBLIC = __AST_DEF (ASTGroup::VISIBILITY_MARKER, 0),
  VISIBILITY_MARKER_PRIVATE = __AST_DEF (ASTGroup::VISIBILITY_MARKER, 1),

  INITLIST_ENTRY = __AST_DEF (ASTGroup::INITLIST, 0),
  INITLIST_ENTRY_EXPLICIT = __AST_DEF (ASTGroup::INITLIST, 1),
  INITLIST_ENTRY_EXPLICIT_ARRAY_ELEM = __AST_DEF (ASTGroup::INITLIST, 2),
};
#undef __AST_DEF

static constexpr ASTGroup
get_ast_group (ASTType type)
{
  return static_cast<ASTGroup> ((static_cast<uint16_t> (type) >> 8) & 0xFF);
}

static constexpr size_t
get_ast_index_in_group (ASTType type)
{
  return static_cast<uint16_t> (type) & 0xFF;
}

struct AST
{
  friend class Parser;
  friend struct Enum;

  AST () = default;
  explicit AST (size_t token_position, ASTType type,
                const std::string &value = "")
      : value{ value }, token_position{ token_position }, type{ type }
  {
  }

  std::string value;
  size_t token_position;
  std::vector<AST> children{};
  ASTType type;

  std::string to_string () const;

  bool is_empty () const;

private:
  size_t _depth{};

  void set_depth (size_t depth);
  AST *append (AST child);
};

}
