#pragma once

#include <string>

enum ESCColor {
  ESCCOLOR_BLACK,
  ESCCOLOR_RED,
  ESCCOLOR_GREEN,
  ESCCOLOR_YELLOW,
  ESCCOLOR_BLUE,
  ESCCOLOR_MAGENTA,
  ESCCOLOR_CYAN,
  ESCCOLOR_WHITE,
  ESCCOLOR_DEFAULT,
};

enum ESCGraphics {
  ESCGRAPHICS_RESET,
  ESCGRAPHICS_BOLD,
  ESCGRAPHICS_DIM,
  ESCGRAPHICS_ITALIC,
  ESCGRAPHICS_UNDERLINE,
  ESCGRAPHICS_BLINK,
  ESCGRAPHICS_INVERSE,
  ESCGRAPHICS_HIDDEN,
  ESCGRAPHICS_STRIKETHROUGH,
};

std::string escape_reset();
std::string escape_color(ESCColor col);
std::string escape_graphics(ESCGraphics mode);
